#!/bin/bash
# =============================================================================
# 13-nginx.sh - Serve the static frontend with nginx, user space, no root
# =============================================================================
# nginx serves the static site directly from disk. There is no frontend build
# step and no node runtime anywhere in the serving path: the site is three HTML
# files, one stylesheet and one script, all of them hand-editable.
#
# History: this step replaced a `pnpm preview` unit that cost 143MB of RAM and
# 308MB of node_modules to serve the same pages on a host with 899MB total.
#
# One origin. nginx serves the files and reverse-proxies:
#     /api/*    -> 127.0.0.1:8081  (messaging-core REST)
#     /stream/* -> 127.0.0.1:8080  (messaging-core WebSocket gateway)
#     /*        -> files on disk
# Because the browser only ever talks to one origin there is no CORS involved
# and messaging-core needs no change.
#
# Everything lives under ~/.witsaba/nginx. Nothing is written outside $HOME and
# no path below 1024 is bound, so no root is required.
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
INSTALL_DIR="$HOME/.witsaba"

. "$SCRIPT_DIR/_lib.sh"

# Homebrew discovery
BREW_BIN=""
for candidate in \
    "/home/linuxbrew/.linuxbrew/bin/brew" \
    "$HOME/.linuxbrew/bin/brew" \
    "$HOME/.brew/bin/brew"; do
    [ -f "$candidate" ] && BREW_BIN="$candidate" && break
done
if [ -z "$BREW_BIN" ]; then
    echo "[x] Homebrew not found. Run 00-brew.sh first." >&2
    exit 1
fi
HOMEBREW_PREFIX="$(dirname "$(dirname "$BREW_BIN")")"
export HOMEBREW_PREFIX
export PATH="$HOMEBREW_PREFIX/bin:$PATH"

echo ""
echo "=============================================="
echo "  Step 13: nginx (static frontend, user space)"
echo "=============================================="
echo ""

# -----------------------------------------------------------------------------
# Tunables
# -----------------------------------------------------------------------------
NGINX_PREFIX="$INSTALL_DIR/nginx"
NGINX_CONF="$NGINX_PREFIX/nginx.conf"
NGINX_HTML="$NGINX_PREFIX/html"
NGINX_LOGS="$NGINX_PREFIX/logs"
NGINX_TEMP="$NGINX_PREFIX/temp"
LISTEN_PORT="${WITSABA_HTTP_PORT:-4173}"

API_PORT="${API_PORT:-8081}"
STREAM_PORT="${STREAM_PORT:-8080}"
GALLERY_PORT="${GALLERY_PORT:-8082}"

NGINX_BIN="$HOMEBREW_PREFIX/bin/nginx"
MIME_TYPES="$HOMEBREW_PREFIX/etc/nginx/mime.types"

# -----------------------------------------------------------------------------
# Install
# -----------------------------------------------------------------------------
if [ ! -x "$NGINX_BIN" ]; then
    log_info "installing nginx via Homebrew..."
    "$BREW_BIN" install nginx
fi
[ -x "$NGINX_BIN" ] || { log_err "nginx binary not found at $NGINX_BIN"; exit 1; }
log_ok "nginx $("$NGINX_BIN" -v 2>&1 | sed 's|.*nginx/||;s/ .*//')"

if [ ! -f "$MIME_TYPES" ]; then
    log_warn "$MIME_TYPES is missing; serving everything as application/octet-stream"
    log_warn "CSS and JS would then be downloaded rather than parsed by the browser"
    MIME_TYPES=""
fi

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------
mkdir -p "$NGINX_HTML" "$NGINX_LOGS" \
         "$NGINX_TEMP/client_body" "$NGINX_TEMP/proxy" \
         "$NGINX_TEMP/fastcgi" "$NGINX_TEMP/uwsgi" "$NGINX_TEMP/scgi"

# -----------------------------------------------------------------------------
# Config
#
# Every path that a system nginx would put in /var is redirected under
# $NGINX_PREFIX, and the `user` directive is omitted because it is only valid
# for the root master process. Without these nginx refuses to start as a normal
# user with "open() ... failed (13: Permission denied)".
#
# daemon off keeps nginx in the foreground so systemd supervises the real
# process instead of tracking a forked child through a pid file.
# -----------------------------------------------------------------------------
{
cat << CONF_HEAD
# witsaba frontend -- generated by 13-nginx.sh, do not edit by hand.
# Regenerate with: ./scripts/install/13-nginx.sh

daemon off;
worker_processes  1;
pid $NGINX_PREFIX/nginx.pid;
error_log $NGINX_LOGS/error.log warn;

events {
    # One worker, a modest cap: this box serves a LAN, not the internet.
    worker_connections 256;
}

http {
CONF_HEAD

if [ -n "$MIME_TYPES" ]; then
    echo "    include $MIME_TYPES;"
fi

cat << CONF_MID
    default_type  application/octet-stream;

    access_log $NGINX_LOGS/access.log;
    client_body_temp_path $NGINX_TEMP/client_body;
    proxy_temp_path       $NGINX_TEMP/proxy;
    fastcgi_temp_path     $NGINX_TEMP/fastcgi;
    uwsgi_temp_path       $NGINX_TEMP/uwsgi;
    scgi_temp_path        $NGINX_TEMP/scgi;

    sendfile      on;
    tcp_nodelay   on;
    keepalive_timeout  65;
    server_tokens off;

    gzip              on;
    gzip_vary         on;
    gzip_min_length   1024;
    gzip_proxied      any;
    gzip_types        text/plain text/css text/javascript
                      application/javascript application/json
                      application/xml image/svg+xml;

    # Do not let a slow client hold a worker open indefinitely.
    client_max_body_size 1m;

    upstream witsaba_api    { server 127.0.0.1:$API_PORT; }
    upstream witsaba_stream { server 127.0.0.1:$STREAM_PORT; }
    upstream witsaba_gallery { server 127.0.0.1:$GALLERY_PORT; }

    server {
        listen $LISTEN_PORT default_server;
        server_name _;

        root $NGINX_HTML;
        index index.html;
        charset utf-8;

        # --- gallery API -> workers -------------------------------------------
        # The workers service owns the capture archive, so it also owns the
        # gallery: listing days, serving a photo, and removing one.
        #
        # This MUST be a longer prefix than the /api/ block below, because
        # nginx routes by LONGEST matching prefix, not by file order. A
        # single location /api/ rule would send every gallery request to
        # messaging-core and answer 404.
        location /api/gallery/ {
            proxy_pass http://witsaba_gallery;
            proxy_http_version 1.1;
            proxy_set_header Host \$host;
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto \$scheme;
            proxy_connect_timeout 5s;
            # Thumbnails are generated on first request, which is a decode
            # plus an encode. Give it headroom over the API's 30s.
            proxy_read_timeout 30s;
            proxy_buffering off;
        }

        # --- REST API -> messaging-core -------------------------------------
        location /api/ {
            proxy_pass http://witsaba_api;
            proxy_http_version 1.1;
            proxy_set_header Host \$host;
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto \$scheme;
            proxy_connect_timeout 5s;
            proxy_read_timeout 30s;
            proxy_buffering off;
        }

        # --- health probe -> messaging-core ----------------------------------
        location = /healthz {
            proxy_pass http://witsaba_stream/healthz;
            proxy_http_version 1.1;
            proxy_set_header Host \$host;
            proxy_connect_timeout 5s;
            proxy_read_timeout 5s;
        }

        # --- camera viewer page -> static file --------------------------------
        # NO BACKTICKS in this block. This heredoc is unquoted, so backticks
        # in these comments are executed as command substitution and the text
        # silently vanishes from the generated config. Use plain paths here.
        #
        # /stream is the viewer page and /stream/<mac> is the WebSocket.
        # Without this block the page is UNREACHABLE. nginx issues a
        # trailing-slash redirect for any URI that is the stem of a prefix
        # location, and it does so BEFORE try_files runs, so /stream is
        # 301'd to /stream/ -- which lands in the proxy block below and 404s
        # at the gateway. stream.html is on disk and serving 200 at
        # /stream.html the whole time; it is simply never consulted.
        # Observed on the Pi: /api and /assets 301 to their slash forms for
        # exactly the same reason, while /devices (no matching prefix
        # location) serves 200 through try_files.
        #
        # An exact '=' match wins over a prefix match, so this takes
        # precedence over the /stream/ proxy block and nothing about the
        # socket path changes.
        location = /stream {
            try_files /stream.html =404;
        }

        # --- camera WebSocket -> messaging-core streaming gateway -------------
        # The upgrade headers are what turn this into a WebSocket instead of a
        # plain proxied request. The long read timeout matters: a camera frame
        # stream is a single long-lived connection, not a burst of requests.
        location /stream/ {
            proxy_pass http://witsaba_stream;
            proxy_http_version 1.1;
            proxy_set_header Upgrade \$http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host \$host;
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            proxy_connect_timeout 5s;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
            # Frames must not be buffered: nginx would hold them until its
            # buffer filled, adding latency to a live view.
            proxy_buffering off;
        }

        # --- static files ---------------------------------------------------
        location /assets/ {
            # Vite-style hashed names are not used here, but assets rarely
            # change between deploys, so a short cache is safe and a revalidate
            # is cheap.
            expires 1h;
            add_header Cache-Control "public, max-age=3600, must-revalidate";
        }

        # index.html must never be cached, or a deploy leaves browsers holding
        # a stale shell that references assets which no longer exist.
        location = /index.html {
            add_header Cache-Control "no-store, no-cache, must-revalidate";
        }

        location = /devices.html {
            add_header Cache-Control "no-store, no-cache, must-revalidate";
        }

        # Same reasoning as index.html and devices.html: a redeploy rewrites
        # app.js/app.css, so a cached page shell can outlive the assets it
        # references.
        location = /stream.html {
            add_header Cache-Control "no-store, no-cache, must-revalidate";
        }

        location / {
            # Clean URLs: /devices must resolve to devices.html on disk.
            # '\$uri \$uri/' alone returns 404, because the file has the
            # extension. '\$uri.html' is tried before the directory form so
            # a page always wins over a same-named directory.
            try_files \$uri \$uri.html \$uri/ =404;
        }

        location = /favicon.svg {
            expires 7d;
        }

        # A reverse proxy in front of a LAN appliance should not advertise
        # framework details in error pages.
        error_page 502 503 504 /50x.html;
        location = /50x.html {
            internal;
            root $NGINX_HTML;
        }
    }
}
CONF_MID
} > "$NGINX_CONF"

log_ok "config written to $NGINX_CONF"

# -----------------------------------------------------------------------------
# 50x page
# -----------------------------------------------------------------------------
cat > "$NGINX_HTML/50x.html" << 'EOF'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Witsaba &middot; unavailable</title>
    <link rel="stylesheet" href="/assets/app.css" />
  </head>
  <body>
    <div class="page">
      <main>
        <div class="panel">
          <div class="panel__body">
            <div class="state state--error">
              <p class="state__title">The witsaba services are not responding</p>
              <p class="state__body">
                nginx is running, but it could not reach messaging-core on the
                backend port. The Go services are probably still starting, or
                have stopped.
              </p>
              <p class="state__error__detail">
                systemctl --user status witsaba-messaging-core
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  </body>
</html>
EOF

# -----------------------------------------------------------------------------
# Deploy the static frontend
# -----------------------------------------------------------------------------
STATIC_SRC="$REPO_DIR/frontend/web_ui/static"
if [ ! -d "$STATIC_SRC" ]; then
    log_err "static frontend not found at $STATIC_SRC"
    exit 1
fi

log_info "deploying static frontend..."
# Replace the contents, not the directory itself: nginx may hold the old tree
# open and the html root is referenced by the running config.
find "$NGINX_HTML" -mindepth 1 -maxdepth 1 ! -name '50x.html' -exec rm -rf {} + 2>/dev/null || true
cp -R "$STATIC_SRC"/. "$NGINX_HTML"/
# The generated 50x page is not part of the repo; keep the deployed copy.
if [ ! -f "$NGINX_HTML/50x.html" ]; then
    log_warn "50x.html was removed by the deploy; regenerating is handled on next run"
fi

DEPLOYED=$(find "$NGINX_HTML" -type f | wc -l | tr -d ' ')
log_ok "deployed $DEPLOYED files, $(du -sh "$NGINX_HTML" | cut -f1) total"

for required in index.html devices.html assets/app.css assets/app.js; do
    if [ ! -f "$NGINX_HTML/$required" ]; then
        log_err "required file missing after deploy: $required"
        exit 1
    fi
done
log_ok "index.html, devices.html, app.css and app.js all present"

# -----------------------------------------------------------------------------
# Validate before anything tries to start it
# -----------------------------------------------------------------------------
log_info "validating config..."
if ! "$NGINX_BIN" -t -c "$NGINX_CONF" -p "$NGINX_PREFIX" 2>&1 | sed 's/^/    /'; then
    log_err "nginx rejected the generated config"
    exit 1
fi

# -----------------------------------------------------------------------------
# Control helpers, mirroring the postgres ones
# -----------------------------------------------------------------------------
cat > "$INSTALL_DIR/nginx/start.sh" << EOF
#!/bin/bash
exec "$NGINX_BIN" -c "$NGINX_CONF" -p "$NGINX_PREFIX"
EOF

cat > "$INSTALL_DIR/nginx/stop.sh" << EOF
#!/bin/bash
"$NGINX_BIN" -c "$NGINX_CONF" -p "$NGINX_PREFIX" -s quit 2>/dev/null
EOF

cat > "$INSTALL_DIR/nginx/reload.sh" << EOF
#!/bin/bash
exec "$NGINX_BIN" -c "$NGINX_CONF" -p "$NGINX_PREFIX" -s reload
EOF

cat > "$INSTALL_DIR/nginx/status.sh" << EOF
#!/bin/bash
if [ -f "$NGINX_PREFIX/nginx.pid" ] && kill -0 "\$(cat "$NGINX_PREFIX/nginx.pid")" 2>/dev/null; then
    echo "nginx running (pid \$(cat "$NGINX_PREFIX/nginx.pid"))"
    exit 0
fi
echo "nginx not running"
exit 3
EOF

chmod +x "$INSTALL_DIR/nginx/"*.sh

echo ""
log_ok "nginx ready"
log_info "  port      : $LISTEN_PORT (all interfaces)"
log_info "  document  : $NGINX_HTML"
log_info "  config    : $NGINX_CONF"
log_info "  /api/*    -> 127.0.0.1:$API_PORT"
log_info "  /stream/* -> 127.0.0.1:$STREAM_PORT"
log_info "  /stream   -> stream.html (camera viewer page)"
log_info ""
log_info "Next: ./12-systemd-services.sh  (creates the witsaba-nginx unit)"
